//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaffgc_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataDesignService : DbContext
    {
        public DataDesignService()
            : base("name=DataDesignService")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DNA> DNAs { get; set; }
        public virtual DbSet<LinkTree> LinkTrees { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberClaim> MemberClaims { get; set; }
        public virtual DbSet<MemberLogin> MemberLogins { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
